<html>
<head><title>Ajout d'un Client </title>
    <link rel="stylesheet" type="text/css" href="bootstrap/css/util.css">
    <link rel="stylesheet" type="text/css" href="bootstrap/css/main.css">
    <link rel="stylesheet" type="text/css" href="bootstrap/bootstrap.min.css">
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  
</head>
<body>
    
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" style="height: 60px;">
        <div class="container">
            
            <button 
                class="navbar-toggler" 
                type="button" 
                data-toggle="collapse" 
                data-target="#navbarResponsive" 
                aria-controls="navbarResponsive" 
                aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active le">
                <a class="nav-link" href="menu.php">Acceuil
                        
                    </a>
                </li>
                <li class="nav-item le">
                <a class="nav-link" href="listeClients.php">Liste de Clients </a>
                </li>
                <li class="nav-item le">
                <a class="nav-link" href="editerClient.php">liste d'attente</a>
                </li>
                <?php if($logged):?>
                <li class="nav-item toRight">
                    <a class="nav-link" href="deconnexion.php">Deconnexion</a>
                </li>
                <?php else:?>
                <li class="nav-item toRight">
                    <a class="nav-link" href="login.php">Connexion</a>
                </li>
                <?php endif;?>
            </ul>
            </div>
        </div>
   </nav>  
        
        <div class="container-contact100 bg">
            <div class="wrap-contact100">
                <form class="contact100-form validate-form" method='POST' enctype="multipart/form-data">
                    <span class="contact100-form-title">
                       <strong> Ajouter un Client  </strong>
                    </span>
                    
                    <div class="wrap-input100 validate-input">
                        <span class="label-input100">Nom du Client </span>
                        <input class="input100" type="text" name="nomClient" value="">
                        <span class="focus-input100"></span>
                    </div>
                    
                    <div class="wrap-input100 validate-input" >
                        <span class="label-input100">Prenom </span>
                        <input class="input100" type="text" name="prenom" value="">
                        <span class="focus-input100"></span>
                    </div>
                    
                    <div class="wrap-input100 validate-input">
                        <span class="label-input100">age</span>
                        <input class="input100" type="text" name="age" value="">
                        <span class="focus-input100"></span>
                    </div>

                    
                    
                    <div class="wrap-input100 validate-input">
                        <span class="label-input100">prescription</span>
                        <input class="input100" type="text" name="prescription" value=""></input>
                        <span class="focus-input100"></span>
                    </div>

                    <label for="file-upload" class="custom-file-upload">
                        Upload
                    </label>
                    <input type="file" id="file-upload" name="photo" />
                    
                    

                    <!-- button Ajouter -->
                    <div class="container-contact100-form-btn">
                        <div class="wrap-contact100-form-btn">
                            <div class="contact100-form-bgbtn"></div>
                            <button class="contact100-form-btn" type="submit" value="envoyer" name="envoyer">
                                <span>
                                    Ajouter un Client 
                                    <i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </form>
		</div>
	</div>
    

</body>
</html>

<script>
    $(function(){
        $("#nav-placeholder").load("navBar.php");
});
</script>
<style>
a {
    font-size: medium;
    font-family: 'Arial';
}
.le {
    position: relative;
    right: 300%;
}
body {
    position: absolute;
    width: 100%;
}
.toRight{
    position: absolute;
    left: 90%;
}
    
.bg {
    margin: 0;
    background: linear-gradient(45deg, #49a09d, #5f2c82);
    font-family: sans-serif;
    font-weight: 100;
}
input[type="file"] {
    display: none;
}
.custom-file-upload {
    border: 1px solid #ccc;
    display: inline-block;
    padding: 6px 12px;
    cursor: pointer;
}
</style>
