<html>
    <head>
        <title>Liste d'attente </title>
        <link 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
            crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    </head>



    <body>
        <div id="nav-placeholder"></div> 
        <div class="container">
            <button 
                class="btn btn-primary btn-margin" 
                onclick="location.href='reserver.php'">
            Reserver  </button>
            <table border ="2" class=" m">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Prenom</th>
                        <th>Age</th>
                        <th>Etat</th>
                        <th>date</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($e as $row): ?>
                    <tr>
                        <td><?php echo $row['id'] ?></td>
                        <td><?php echo $row['nom'] ?></td>
                        <td><?php echo $row['prenom'] ?></td>
                        <td><?php echo $row['age'] ?></td>
                        <?php if($row['etat']==0):?>
                        <td>
                            <span class="badge bg-warning text-dark">En attente</span>
                        </td>
                        <?php elseif ($row['etat']==1): ?>
                            <td>
                            <span class="badge bg-success">accepter</span>
                        </td>
                        <?php else :?>
                            <td>
                            <span class="badge bg-danger">refuser</span>
                        </td>
                        <?php endif?>
                        <td><?php echo $row['date'] ?></td>
                        <?php if($_SESSION['isAdmin']): ?>
                            <td>
                                <button 
                                class="btn btn-success"
                                    onclick="location.href='accepterReservation.php?id=<?=$row['id']?>'"
                                    >accepter</button>
                            </td>
                            <td>
                                <button 
                                    class="btn btn-danger" 
                                    onclick="location.href='supprimerReservation.php?id=<?=$row['id']?>'"
                                    >refuser
                                </button>
                            </td>
                        <?php endif;?>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </body>
</html>

<style>
.btn-margin{
    position: absolute;
    margin-top: 6%;
    margin-left: 66%;
}
.m {
    position: absolute;
    margin-top: 10%;
}
html,bodyheader,
        .view {
    height: 100%;
    background-color:repeat-y;
}

body {
	margin: 0;
	background: linear-gradient(45deg, #49a09d, #5f2c82);
	font-family: sans-serif;
	font-weight: 100;
}

.container {
	position: absolute;
	top: 30%;
	left: 50%;
	transform: translate(-50%, -50%);
}
caption{
    font-size: 20px;
    caption-side:top;
    color: black;
    font-weight: bold;
    text-align: center;
    margin: 10px;
}
table {
    position: relative;
	left: 20%;  
	width: 800px;
	border-collapse: collapse;
	overflow: hidden;
	box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
}

th,
td {
	padding: 15px;
	background-color: rgba(255, 255, 255, 0.2);
	color: #fff;
    
}

th {
	text-align: left;
}

thead>tr>th {
            background-color: #55608f;
        }
    

tbody>tr:hover {
			background-color: rgba(255, 255, 255, 0.3);
		}
	
    tbody>td {
        position: relative;
    }
    tbody>td:hover:before 
			 {
				content: "";
				position: absolute;
				left: 0;
				right: 0;
				top: -9999px;
				bottom: -9999px;
				background-color: rgba(255, 255, 255, 0.2);
				z-index: -1;
			}

@media (max-width: 740px) {
  html,
  body,
  header,
  .view {
    height: 1000px;
  }
}

@media (min-width: 800px) and (max-width: 850px) {
  html,
  body,
  header,
  .view {
    height: 650px;
  }
}
@media (min-width: 800px) and (max-width: 850px) {
  .navbar:not(.top-nav-collapse) {
     background: #1C2331!important;
  }
}
#nav-placeholder{
    position: absolute;
    height: 100px;
    width: 100%;
}
</style>
<script>
$(function(){
  $("#nav-placeholder").load("navBar.php");
});
</script>