
<!DOCTYPE html>
<html>
    <head>
        <link 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
            crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-1.10.2.js">
        
      </script>
        
    </head>
    <body>
        <!--Navigation bar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" style="height: 60px;">
        <div class="container">
            
            <button 
                class="navbar-toggler" 
                type="button" 
                data-toggle="collapse" 
                data-target="#navbarResponsive" 
                aria-controls="navbarResponsive" 
                aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active le">
                <a class="nav-link" href="menu.php">Acceuil
                        
                    </a>
                </li>
                <li class="nav-item le">
                <a class="nav-link" href="listeClients.php">Liste de Clients</a>
                </li>
                <li class="nav-item le">
                <a class="nav-link" href="editerClient.php">liste d'attente</a>
                </li>
                <?php if($logged):?>
                <li class="nav-item toRight">
                    <a class="nav-link" href="deconnexion.php">Deconnexion</a>
                </li>
                <?php else:?>
                <li class="nav-item toRight">
                    <a class="nav-link" href="login.php">Connexion</a>
                </li>
                <?php endif;?>
            </ul>
            </div>
        </div>
   </nav>

  <!-- Full Page Intro -->
    <div class="view full-page-intro">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

        <!-- Content -->
        <div class="container mt-5">

            <!--Grid row-->
            <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-12 mb-6 white-text text-center text-md-left">

                <h1 class="display-4 font-weight-bold">bienvenue <?php if(isset($_SESSION['user'])) echo ' ,'.$name ;?></h1> 
        
                <hr class="hr-light">
                <div class="row mt-5">
                  <div class="col-md-6">

                    <a href="listeClients.php">
                      <div class="card" style="width: 90%; height:150px; background-color:transparent;">
                        <!-- <img class="card-img-top" src="" alt="Card image cap"> -->
                        <div class="card-body">
                          <h5 class="card-title mt-4">Liste de Clients </h5>
                          
                        </div>
                      </div>
                    </a>
                  </div>
                

                  
                  <div class="col-md-6">

                    <a href="listeAttente.php">
                      <div class="card" style="width: 90%; height:150px; background-color:transparent;">
                        <!-- <img class="card-img-top" src="" alt="Card image cap"> -->
                        <div class="card-body">
                          <h5 class="card-title mt-4">liste d'attente</h5>
                          <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                          <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                        </div>
                      </div>
                    </a>
                    
                  </div>
                </div>

            </div>
            <!--Grid column-->


            </div>
            <!--Grid row-->

        </div>
        <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

    </div>
  <!-- Full Page Intro -->


        <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" 
        crossorigin="anonymous">
        </script>
    </body>
</html>
<style>
  nav a {
    font-size: medium;
    font-family: 'Arial';
}
.le {
    position: relative;
    right: 0%;
}
body {
    position: absolute;
    width: 100%;
}
.toRight{
    position: absolute;
    left: 90%;
}
a {
  color: black;
}
a:hover {
  color: white;
}
html,body,header,
        .view {
        height: 100%;
    }
body {
	margin: 0;
	background: linear-gradient(45deg, #49a09d, #5f2c82);
	font-family: sans-serif;
	font-weight: 100;
}
@media (max-width: 740px) {
  html,
  body,
  header,
  .view {
    height: 1000px;
  }
}

@media (min-width: 800px) and (max-width: 850px) {
  html,
  body,
  header,
  .view {
    height: 650px;
  }
}
@media (min-width: 800px) and (max-width: 850px) {
  .navbar:not(.top-nav-collapse) {
     background: #1C2331!important;
  }
}


</style>


<script>
$(function(){
  $("#nav-placeholder").load("navBar.php");
});
</script>

