<!DOCTYPE html>
<html>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
        crossorigin="anonymous">
    <body>

    <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" style="height: 60px;">
        <div class="container">
            
            <button 
                class="navbar-toggler" 
                type="button" 
                data-toggle="collapse" 
                data-target="#navbarResponsive" 
                aria-controls="navbarResponsive" 
                aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="menu.php">Acceuil
                        <!-- <span class="sr-only">(current)</span> -->
                    </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="listeClients.php">Liste Clients </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="listeAttente.php">liste d'attente</a>
                </li>
                <?php if($logged):?>
                <li class="nav-item toRight">
                    <a class="nav-link" href="deconnexion.php">Deconnexion</a>
                </li>
                <?php else:?>
                <li class="nav-item toRight">
                    <a class="nav-link" href="login.php">Connexion</a>
                </li>
                <?php endif;?>
            </ul>
            </div>
        </div>
        </nav>
        

        <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" 
        crossorigin="anonymous">
        </script>
    </body>
</html>
<style>
    
    body {
        position: absolute;
        width: 100%;
    }
    .toRight{
        position: absolute;
        left: 100%;
    }
</style>